env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: "commonjs"
  project: "tsconfig.json"
plugins:
  - "@typescript-eslint"
rules: { "no-console": ["error", { allow: ["warn", "error"] }] }
